version: "3.0"

services:
  nginx:
    build: ./nginx
    links:
      - chat-service
      - auth-service
      - web-sockets-1
      - web-sockets-2
    ports:
     - "3000:80"
    networks:
     - webnet

  chat-service:
    build: ../chat-service
    links:
      - redis
      - postgres
    expose:
      - "8000"
    environment:
      - NAME=chat
    networks:
      - webnet

  auth-service:
    build: ../auth-service
    links:
     - redis
     - postgres
    expose:
     - "8000"
    environment:
     - NAME=auth
    networks:
     - webnet

  web-sockets-1:
    build: ../web-sockets
    links:
      - redis
    expose:
      - "8000"
    environment:
      - NAME=WS-1
      - PORT=8000
    networks:
      - webnet

  web-sockets-2:
      build: ../web-sockets
      links:
        - redis
      expose:
        - "8000"
      environment:
        - NAME=WS-2
        - PORT=8000
      networks:
        - webnet


  postgres:
    image: postgres
    expose:
    - "5432"
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
     - ./volumes/postgres:/var/lib/postgresql/data
    networks:
     - webnet

  migration:
    build: ../database-module
    command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "-s", "-t", "0", "--", "npm", "run", "setupDB"]
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - webnet


  redis:
    image: redis
    expose:
      - "6379"
    volumes:
      - ./volumes/redis:/data
    ports:
      - 6379:6379
    networks:
      - webnet

networks:
  webnet:
